const QUESTION_BANK = {
  easy: [
    { q: "2 + 3 = ?", o: [4, 5, 6, 7], a: 5 },
    { q: "5 + 7 = ?", o: [10, 11, 12, 13], a: 12 },
    { q: "10 - 4 = ?", o: [5, 6, 7, 8], a: 6 },
    { q: "3 × 4 = ?", o: [7, 10, 12, 14], a: 12 },
    { q: "12 ÷ 3 = ?", o: [2, 3, 4, 5], a: 4 },
    { q: "Which is a color?", o: ["Dog", "Blue", "Car", "Chair"], a: "Blue" },
    { q: "Which is bigger?", o: [5, 9, 2, 1], a: 9 },
    { q: "How many days in a week?", o: [5, 6, 7, 8], a: 7 },
    { q: "What comes after B?", o: ["A", "C", "D", "E"], a: "C" },
    { q: "Which one is a fruit?", o: ["Potato", "Apple", "Onion", "Carrot"], a: "Apple" },
    { q: "1 + 1 = ?", o: [1, 2, 3, 4], a: 2 },
    { q: "4 + 6 = ?", o: [9, 10, 11, 12], a: 10 },
    { q: "8 - 3 = ?", o: [3, 4, 5, 6], a: 5 },
    { q: "2 × 5 = ?", o: [8, 9, 10, 11], a: 10 },
    { q: "9 ÷ 3 = ?", o: [2, 3, 4, 5], a: 3 },
    { q: "The Sun rises from the...?", o: ["West", "East", "North", "South"], a: "East" },
    { q: "Which is an animal?", o: ["Rock", "Car", "Cat", "Table"], a: "Cat" },
    { q: "How many hours in a day?", o: [12, 18, 24, 36], a: 24 },
    { q: "What comes before D?", o: ["A", "B", "C", "E"], a: "C" },
    { q: "Which shape is round?", o: ["Box", "Circle", "Book", "Door"], a: "Circle" }
  ],

  medium: [
    { q: "3, 6, 9, ?", o: [10, 11, 12, 13], a: 12 },
    { q: "5² = ?", o: [10, 15, 20, 25], a: 25 },
    { q: "What is 15% of 200?", o: [20, 25, 30, 35], a: 30 },
    { q: "Which is a prime number?", o: [4, 6, 9, 11], a: 11 },
    { q: "Square root of 49?", o: [6, 7, 8, 9], a: 7 },
    { q: "12 × 8 = ?", o: [88, 92, 96, 100], a: 96 },
    { q: "100 ÷ 4 = ?", o: [20, 25, 30, 40], a: 25 },
    { q: "Which is NOT a planet?", o: ["Mars", "Earth", "Moon", "Venus"], a: "Moon" },
    { q: "Opposite of Hot?", o: ["Warm", "Cool", "Cold", "Dry"], a: "Cold" },
    { q: "If A=1, B=2, then C=?", o: [2, 3, 4, 5], a: 3 },
    { q: "7 × 9 = ?", o: [56, 63, 72, 81], a: 63 },
    { q: "144 ÷ 12 = ?", o: [10, 11, 12, 13], a: 12 },
    { q: "Which number is even?", o: [3, 5, 7, 8], a: 8 },
    { q: "Sequence: 2, 4, 8, ?", o: [10, 12, 14, 16], a: 16 },
    { q: "What is the capital of Japan?", o: ["Osaka", "Kyoto", "Tokyo", "Seoul"], a: "Tokyo" },
    { q: "Which is heavier?", o: ["1kg iron", "1kg cotton", "They are the same", "None"], a: "They are the same" },
    { q: "What is 25% of 80?", o: [15, 20, 25, 30], a: 20 },
    { q: "Which number is divisible by 3?", o: [10, 11, 12, 14], a: 12 },
    { q: "Which is a mammal?", o: ["Snake", "Shark", "Whale", "Frog"], a: "Whale" },
    { q: "What is the common name for H2O?", o: ["Salt", "Oxygen", "Water", "Hydrogen"], a: "Water" }
  ],

  hard: [
    { q: "Fibonacci: 1, 1, 2, 3, 5, ?", o: [6, 7, 8, 9], a: 8 },
    { q: "Solve for x: 3x = 12", o: [2, 3, 4, 5], a: 4 },
    { q: "Which shape can be non-symmetric?", o: ["Circle", "Square", "Scalene Triangle", "Rectangle"], a: "Scalene Triangle" },
    { q: "Binary representation of 5?", o: ["101", "110", "111", "100"], a: "101" },
    { q: "Find the odd one out:", o: ["Cube", "Sphere", "Cylinder", "Circle"], a: "Circle" },
    { q: "2 to the power of 5 (2⁵) = ?", o: [16, 24, 32, 64], a: 32 },
    { q: "What is log10(100)?", o: [1, 2, 3, 4], a: 2 },
    { q: "Degrees in a straight line?", o: ["90°", "120°", "180°", "360°"], a: "180°" },
    { q: "Which is an irrational number?", o: ["2", "4", "√2", "8"], a: "√2" },
    { q: "Logic: If all BLOOPS are RAZZIES and all RAZZIES are JAZZIES, are BLOOPS JAZZIES?", o: ["True", "False", "Cannot say", "None"], a: "True" },
    { q: "Sequence: 2, 6, 12, 20, ?", o: [24, 30, 32, 42], a: 30 },
    { q: "Missing square number: 4, 9, 16, ?", o: [20, 24, 25, 36], a: 25 },
    { q: "If today is Monday, what day is it in 100 days?", o: ["Tuesday", "Wednesday", "Thursday", "Friday"], a: "Wednesday" },
    { q: "Which shape has the most sides?", o: ["Hexagon", "Pentagon", "Octagon", "Heptagon"], a: "Octagon" },
    { q: "Find the odd number: 2, 3, 5, 9, 11", o: [3, 5, 9, 11], a: 9 },
    { q: "What is the average of 10 and 20?", o: [10, 15, 20, 25], a: 15 },
    { q: "Which is NOT a programming language?", o: ["Python", "Java", "HTML", "Elephant"], a: "Elephant" },
    { q: "Convert binary 111 to decimal:", o: [5, 6, 7, 8], a: 7 },
    { q: "If 5 people take 5 min to eat 5 apples, how long does 1 person take to eat 1 apple?", o: [1, 5, 10, 25], a: 5 },
    { q: "Alphabet sequence: Z, X, V, ?", o: ["U", "T", "S", "R"], a: "T" }
  ]
};